package support.web.view;

import support.annotation.Container;
import webserver.request.HttpRequest;
import webserver.response.HttpResponse;

@Container
public class PostShowView implements View {

    @Override
    public String view(HttpRequest request, HttpResponse response) {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder
                .append("<!DOCTYPE html>")
                .append("<html lang=\"kr\">")
                .append("<head>")
                .append("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">")
                .append("    <meta charset=\"utf-8\">")
                .append("    <title>SLiPP Java Web Programming</title>")
                .append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">")
                .append("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">")
                .append("    <!--[if lt IE 9]>")
                .append("    <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>")
                .append("    <![endif]-->")
                .append("    <link href=\"../css/styles.css\" rel=\"stylesheet\">")
                .append("</head>")
                .append("<body>")
                .append("<nav class=\"navbar navbar-fixed-top header\">")
                .append("    <div class=\"col-md-12\">")
                .append("        <div class=\"navbar-header\">")
                .append("")
                .append("            <a href=\"../index\" class=\"navbar-brand\">SLiPP</a>")
                .append("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse1\">")
                .append("                <i class=\"glyphicon glyphicon-search\"></i>")
                .append("            </button>")
                .append("")
                .append("        </div>")
                .append("        <div class=\"collapse navbar-collapse\" id=\"navbar-collapse1\">")
                .append("            <form class=\"navbar-form pull-left\">")
                .append("                <div class=\"input-group\" style=\"max-width:470px;\">")
                .append("                    <input type=\"text\" class=\"form-control\" placeholder=\"Search\" name=\"srch-term\" id=\"srch-term\">")
                .append("                    <div class=\"input-group-btn\">")
                .append("                        <button class=\"btn btn-default btn-primary\" type=\"submit\"><i class=\"glyphicon glyphicon-search\"></i></button>")
                .append("                    </div>")
                .append("                </div>")
                .append("            </form>")
                .append("            <ul class=\"nav navbar-nav navbar-right\">")
                .append("                <li>")
                .append("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-bell\"></i></a>")
                .append("                    <ul class=\"dropdown-menu\">")
                .append("                        <li><a href=\"https://slipp.net\" target=\"_blank\">SLiPP</a></li>")
                .append("                        <li><a href=\"https://facebook.com\" target=\"_blank\">Facebook</a></li>")
                .append("                    </ul>")
                .append("                </li>")
                .append("                <li><a href=\"../user/list\"><i class=\"glyphicon glyphicon-user\"></i></a></li>")
                .append("            </ul>")
                .append("        </div>")
                .append("    </div>")
                .append("</nav>")
                .append("<div class=\"navbar navbar-default\" id=\"subnav\">")
                .append("    <div class=\"col-md-12\">")
                .append("        <div class=\"navbar-header\">")
                .append("            <a href=\"#\" style=\"margin-left:15px;\" class=\"navbar-btn btn btn-default btn-plus dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-home\" style=\"color:#dd1111;\"></i> Home <small><i class=\"glyphicon glyphicon-chevron-down\"></i></small></a>")
                .append("            <ul class=\"nav dropdown-menu\">")
                .append("                <li><a href=\"../user/profile.html\"><i class=\"glyphicon glyphicon-user\" style=\"color:#1111dd;\"></i> Profile</a></li>")
                .append("                <li class=\"nav-divider\"></li>")
                .append("                <li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\" style=\"color:#dd1111;\"></i> Settings</a></li>")
                .append("            </ul>")
                .append("            ")
                .append("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse2\">")
                .append("            	<span class=\"sr-only\">Toggle navigation</span>")
                .append("            	<span class=\"icon-bar\"></span>")
                .append("            	<span class=\"icon-bar\"></span>")
                .append("            	<span class=\"icon-bar\"></span>")
                .append("            </button>            ")
                .append("        </div>")
                .append("        <div class=\"collapse navbar-collapse\" id=\"navbar-collapse2\">")
                .append("            <ul class=\"nav navbar-nav navbar-right\">")
                .append("                <li class=\"active\"><a href=\"../index\">Posts</a></li>")
                .append("                <li><a href=\"../user/login.html\" role=\"button\">로그인</a></li>")
                .append("                <li><a href=\"../user/form.html\" role=\"button\">회원가입</a></li>")
                .append("                <li><a href=\"#\" role=\"button\">로그아웃</a></li>")
                .append("                <li><a href=\"#\" role=\"button\">개인정보수정</a></li>")
                .append("            </ul>")
                .append("        </div>")
                .append("    </div>")
                .append("</div>")
                .append("")
                .append("<div class=\"container\" id=\"main\">")
                .append("    <div class=\"col-md-12 col-sm-12 col-lg-12\">")
                .append("        <div class=\"panel panel-default\">")
                .append("          <header class=\"qna-header\">")
                .append("              <h2 class=\"qna-title\">InitializingBean implements afterPropertiesSet() 호출되지 않는 문제.</h2>")
                .append("          </header>")
                .append("          <div class=\"content-main\">")
                .append("              <article class=\"article\">")
                .append("                  <div class=\"article-header\">")
                .append("                      <div class=\"article-header-thumb\">")
                .append("                          <img src=\"https://graph.facebook.com/v2.3/100000059371774/picture\" class=\"article-author-thumb\" alt=\"\">")
                .append("                      </div>")
                .append("                      <div class=\"article-header-text\">")
                .append("                          <a href=\"/users/92/kimmunsu\" class=\"article-author-name\">kimmunsu</a>")
                .append("                          <a href=\"/questions/413\" class=\"article-header-time\" title=\"퍼머링크\">")
                .append("                              2015-12-30 01:47")
                .append("                              <i class=\"icon-link\"></i>")
                .append("                          </a>")
                .append("                      </div>")
                .append("                  </div>")
                .append("                  <div class=\"article-doc\">")
                .append("                      <p>A 에 의존성을 가지는 B라는 클래스가 있습니다.</p><p>B라는 클래스는 InitializingBean 을 상속하고 afterPropertiesSet을 구현하고 있습니다.")
                .append("                      서버가 가동되면서 bean들이 초기화되는 시점에 B라는 클래스의 afterPropertiesSet 메소드는</p><p>A라는 클래스의 특정 메소드인 afunc()를 호출하고 있습니다.</p>")
                .append("                  </div>")
                .append("                  <div class=\"article-utils\">")
                .append("                      <ul class=\"article-utils-list\">")
                .append("                          <li>")
                .append("                              <a class=\"link-modify-article\" href=\"/questions/423/form\">수정</a>")
                .append("                          </li>")
                .append("                          <li>")
                .append("                              <form class=\"form-delete\" action=\"/questions/423\" method=\"POST\">")
                .append("                                  <input type=\"hidden\" name=\"_method\" value=\"DELETE\">")
                .append("                                  <button class=\"link-delete-article\" type=\"submit\">삭제</button>")
                .append("                              </form>")
                .append("                          </li>")
                .append("                          <li>")
                .append("                              <a class=\"link-modify-article\" href=\"/index\">목록</a>")
                .append("                          </li>")
                .append("                      </ul>")
                .append("                  </div>")
                .append("              </article>")
                .append("")
                .append("              <div class=\"qna-comment\">")
                .append("                  <div class=\"qna-comment-slipp\">")
                .append("                      <p class=\"qna-comment-count\"><strong>2</strong>개의 의견</p>")
                .append("                      <div class=\"qna-comment-slipp-articles\">")
                .append("")
                .append("                          <article class=\"article\" id=\"answer-1405\">")
                .append("                              <div class=\"article-header\">")
                .append("                                  <div class=\"article-header-thumb\">")
                .append("                                      <img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">")
                .append("                                  </div>")
                .append("                                  <div class=\"article-header-text\">")
                .append("                                      <a href=\"/users/1/자바지기\" class=\"article-author-name\">자바지기</a>")
                .append("                                      <a href=\"#answer-1434\" class=\"article-header-time\" title=\"퍼머링크\">")
                .append("                                          2016-01-12 14:06")
                .append("                                      </a>")
                .append("                                  </div>")
                .append("                              </div>")
                .append("                              <div class=\"article-doc comment-doc\">")
                .append("                                  <p>이 글만으로는 원인 파악하기 힘들겠다. 소스 코드와 설정을 단순화해서 공유해 주면 같이 디버깅해줄 수도 있겠다.</p>")
                .append("                              </div>")
                .append("                              <div class=\"article-utils\">")
                .append("                                  <ul class=\"article-utils-list\">")
                .append("                                      <li>")
                .append("                                          <a class=\"link-modify-article\" href=\"/questions/413/answers/1405/form\">수정</a>")
                .append("                                      </li>")
                .append("                                      <li>")
                .append("                                          <form class=\"delete-answer-form\" action=\"/questions/413/answers/1405\" method=\"POST\">")
                .append("                                              <input type=\"hidden\" name=\"_method\" value=\"DELETE\">")
                .append("                                              <button type=\"submit\" class=\"delete-answer-button\">삭제</button>")
                .append("                                          </form>")
                .append("                                      </li>")
                .append("                                  </ul>")
                .append("                              </div>")
                .append("                          </article>")
                .append("                          <article class=\"article\" id=\"answer-1406\">")
                .append("                              <div class=\"article-header\">")
                .append("                                  <div class=\"article-header-thumb\">")
                .append("                                      <img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">")
                .append("                                  </div>")
                .append("                                  <div class=\"article-header-text\">")
                .append("                                      <a href=\"/users/1/자바지기\" class=\"article-author-name\">자바지기</a>")
                .append("                                      <a href=\"#answer-1434\" class=\"article-header-time\" title=\"퍼머링크\">")
                .append("                                          2016-01-12 14:06")
                .append("                                      </a>")
                .append("                                  </div>")
                .append("                              </div>")
                .append("                              <div class=\"article-doc comment-doc\">")
                .append("                                  <p>이 글만으로는 원인 파악하기 힘들겠다. 소스 코드와 설정을 단순화해서 공유해 주면 같이 디버깅해줄 수도 있겠다.</p>")
                .append("                              </div>")
                .append("                              <div class=\"article-utils\">")
                .append("                                  <ul class=\"article-utils-list\">")
                .append("                                      <li>")
                .append("                                          <a class=\"link-modify-article\" href=\"/questions/413/answers/1405/form\">수정</a>")
                .append("                                      </li>")
                .append("                                      <li>")
                .append("                                          <form class=\"delete-answer-form\" action=\"/questions/413/answers/1405\" method=\"POST\">")
                .append("                                              <input type=\"hidden\" name=\"_method\" value=\"DELETE\">")
                .append("                                              <button type=\"submit\" class=\"delete-answer-button\">삭제</button>")
                .append("                                          </form>")
                .append("                                      </li>")
                .append("                                  </ul>")
                .append("                              </div>")
                .append("                          </article>")
                .append("                          <form class=\"answer-form\">")
                .append("                              <div class=\"form-group\" style=\"padding:14px;\">")
                .append("                                  <textarea class=\"form-control\" placeholder=\"Update your status\"></textarea>")
                .append("                              </div>")
                .append("                              <button class=\"btn btn-success pull-right\" type=\"button\">답변하기</button>")
                .append("                              <div class=\"clearfix\" />")
                .append("                          </form>")
                .append("                      </div>")
                .append("                  </div>")
                .append("              </div>")
                .append("          </div>")
                .append("        </div>")
                .append("    </div>")
                .append("</div>")
                .append("")
                .append("<script type=\"text/template\" id=\"answerTemplate\">")
                .append("	<article class=\"article\">")
                .append("		<div class=\"article-header\">")
                .append("			<div class=\"article-header-thumb\">")
                .append("				<img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">")
                .append("			</div>")
                .append("			<div class=\"article-header-text\">")
                .append("				<a href=\"#\" class=\"article-author-name\">{0}</a>")
                .append("				<div class=\"article-header-time\">{1}</div>")
                .append("			</div>")
                .append("		</div>")
                .append("		<div class=\"article-doc comment-doc\">")
                .append("			{2}")
                .append("		</div>")
                .append("		<div class=\"article-utils\">")
                .append("		<ul class=\"article-utils-list\">")
                .append("			<li>")
                .append("				<a class=\"link-modify-article\" href=\"/api/questions/{3}/answers/{4}/form\">수정</a>				")
                .append("			</li>")
                .append("			<li>")
                .append("				<form class=\"delete-answer-form\" action=\"/api/questions/{3}/answers/{4}\" method=\"POST\">")
                .append("					<input type=\"hidden\" name=\"_method\" value=\"DELETE\">")
                .append("                     <button type=\"submit\" class=\"delete-answer-button\">삭제</button>")
                .append("				</form>")
                .append("			</li>")
                .append("		</ul>")
                .append("		</div>")
                .append("	</article>")
                .append("</script>")
                .append("")
                .append("<!-- script references -->")
                .append("<script src=\"../js/jquery-2.2.0.min.js\"></script>")
                .append("<script src=\"../js/bootstrap.min.js\"></script>")
                .append("<script src=\"../js/scripts.js\"></script>")
                .append("	</body>")
                .append("</html>");

        return stringBuilder.toString();
    }

}
