package view;

import annotation.View;
import db.ContentDatabase;
import model.Content;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import webserver.HTTPServletRequest;

@View(path = "/qna/show.html")
public class ContentView implements ViewBase{

    private static final Logger logger = LoggerFactory.getLogger(ContentView.class);
    public String changeToDynamic(HTTPServletRequest request){
        StringBuilder sb = new StringBuilder();
        int index = Integer.parseInt(request.getQuery().get("index"));
        Content findContent = ContentDatabase.findById(index);

        logger.debug("findContent = {}", findContent.getContents());

        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"kr\">\n");
        sb.append("<head>\n");
        sb.append("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
        sb.append("    <meta charset=\"utf-8\">\n");
        sb.append("    <title>SLiPP Java Web Programming</title>\n");
        sb.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
        sb.append("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\n");
        sb.append("    <!--[if lt IE 9]>\n");
        sb.append("    <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
        sb.append("    <![endif]-->\n");
        sb.append("    <link href=\"../css/styles.css\" rel=\"stylesheet\">\n");
        sb.append("</head>\n");
        sb.append("<body>\n");
        sb.append("<nav class=\"navbar navbar-fixed-top header\">\n");
        sb.append("    <div class=\"col-md-12\">\n");
        sb.append("        <div class=\"navbar-header\">\n");
        sb.append("\n");
        sb.append("            <a href=\"../index.html\" class=\"navbar-brand\">SLiPP</a>\n");
        sb.append("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse1\">\n");
        sb.append("                <i class=\"glyphicon glyphicon-search\"></i>\n");
        sb.append("            </button>\n");
        sb.append("\n");
        sb.append("        </div>\n");
        sb.append("        <div class=\"collapse navbar-collapse\" id=\"navbar-collapse1\">\n");
        sb.append("            <form class=\"navbar-form pull-left\">\n");
        sb.append("                <div class=\"input-group\" style=\"max-width:470px;\">\n");
        sb.append("                    <input type=\"text\" class=\"form-control\" placeholder=\"Search\" name=\"srch-term\" id=\"srch-term\">\n");
        sb.append("                    <div class=\"input-group-btn\">\n");
        sb.append("                        <button class=\"btn btn-default btn-primary\" type=\"submit\"><i class=\"glyphicon glyphicon-search\"></i></button>\n");
        sb.append("                    </div>\n");
        sb.append("                </div>\n");
        sb.append("            </form>\n");
        sb.append("            <ul class=\"nav navbar-nav navbar-right\">\n");
        sb.append("                <li>\n");
        sb.append("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-bell\"></i></a>\n");
        sb.append("                    <ul class=\"dropdown-menu\">\n");
        sb.append("                        <li><a href=\"https://slipp.net\" target=\"_blank\">SLiPP</a></li>\n");
        sb.append("                        <li><a href=\"https://facebook.com\" target=\"_blank\">Facebook</a></li>\n");
        sb.append("                    </ul>\n");
        sb.append("                </li>\n");
        sb.append("                <li><a href=\"../user/list.html\"><i class=\"glyphicon glyphicon-user\"></i></a></li>\n");
        sb.append("            </ul>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("</nav>\n");
        sb.append("<div class=\"navbar navbar-default\" id=\"subnav\">\n");
        sb.append("    <div class=\"col-md-12\">\n");
        sb.append("        <div class=\"navbar-header\">\n");
        sb.append("            <a href=\"#\" style=\"margin-left:15px;\" class=\"navbar-btn btn btn-default btn-plus dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-home\" style=\"color:#dd1111;\"></i> Home <small><i class=\"glyphicon glyphicon-chevron-down\"></i></small></a>\n");
        sb.append("            <ul class=\"nav dropdown-menu\">\n");
        sb.append("                <li><a href=\"../user/profile.html\"><i class=\"glyphicon glyphicon-user\" style=\"color:#1111dd;\"></i> Profile</a></li>\n");
        sb.append("                <li class=\"nav-divider\"></li>\n");
        sb.append("                <li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\" style=\"color:#dd1111;\"></i> Settings</a></li>\n");
        sb.append("            </ul>\n");
        sb.append("            \n");
        sb.append("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse2\">\n");
        sb.append("            \t<span class=\"sr-only\">Toggle navigation</span>\n");
        sb.append("            \t<span class=\"icon-bar\"></span>\n");
        sb.append("            \t<span class=\"icon-bar\"></span>\n");
        sb.append("            \t<span class=\"icon-bar\"></span>\n");
        sb.append("            </button>            \n");
        sb.append("        </div>\n");
        sb.append("        <div class=\"collapse navbar-collapse\" id=\"navbar-collapse2\">\n");
        sb.append("            <ul class=\"nav navbar-nav navbar-right\">\n");
        sb.append("                <li class=\"active\"><a href=\"../index.html\">Posts</a></li>\n");
        sb.append("                <li><a href=\"../user/login.html\" role=\"button\">로그인</a></li>\n");
        sb.append("                <li><a href=\"../user/form.html\" role=\"button\">회원가입</a></li>\n");
        sb.append("                <li><a href=\"#\" role=\"button\">로그아웃</a></li>\n");
        sb.append("                <li><a href=\"#\" role=\"button\">개인정보수정</a></li>\n");
        sb.append("            </ul>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("</div>\n");
        sb.append("\n");
        sb.append("<div class=\"container\" id=\"main\">\n");
        sb.append("    <div class=\"col-md-12 col-sm-12 col-lg-12\">\n");
        sb.append("        <div class=\"panel panel-default\">\n");
        sb.append("          <header class=\"qna-header\">\n");
        sb.append("              <h2 class=\"qna-title\">" + findContent.getTitle() + "</h2>\n");
        sb.append("          </header>\n");
        sb.append("          <div class=\"content-main\">\n");
        sb.append("              <article class=\"article\">\n");
        sb.append("                  <div class=\"article-header\">\n");
        sb.append("                      <div class=\"article-header-thumb\">\n");
        sb.append("                          <img src=\"https://graph.facebook.com/v2.3/100000059371774/picture\" class=\"article-author-thumb\" alt=\"\">\n");
        sb.append("                      </div>\n");
        sb.append("                      <div class=\"article-header-text\">\n");
        sb.append("                          <a href=\"/users/92/kimmunsu\" class=\"article-author-name\">" + findContent.getWriter() + "</a>\n");
        sb.append("                          <a href=\"/questions/413\" class=\"article-header-time\" title=\"퍼머링크\">\n");
        sb.append("                              2015-12-30 01:47\n");
        sb.append("                              <i class=\"icon-link\"></i>\n");
        sb.append("                          </a>\n");
        sb.append("                      </div>\n");
        sb.append("                  </div>\n");
        sb.append("                  <div class=\"article-doc\">\n");
        sb.append("                      <p>" + findContent.getContents() + "</p>\n");
        sb.append("                  </div>\n");
        sb.append("                  <div class=\"article-utils\">\n");
        sb.append("                      <ul class=\"article-utils-list\">\n");
        sb.append("                          <li>\n");
        sb.append("                              <a class=\"link-modify-article\" href=\"/questions/423/form\">수정</a>\n");
        sb.append("                          </li>\n");
        sb.append("                          <li>\n");
        sb.append("                              <form class=\"form-delete\" action=\"/questions/423\" method=\"POST\">\n");
        sb.append("                                  <input type=\"hidden\" name=\"_method\" value=\"DELETE\">\n");
        sb.append("                                  <button class=\"link-delete-article\" type=\"submit\">삭제</button>\n");
        sb.append("                              </form>\n");
        sb.append("                          </li>\n");
        sb.append("                          <li>\n");
        sb.append("                              <a class=\"link-modify-article\" href=\"/index.html\">목록</a>\n");
        sb.append("                          </li>\n");
        sb.append("                      </ul>\n");
        sb.append("                  </div>\n");
        sb.append("              </article>\n");
        sb.append("\n");
        sb.append("              <div class=\"qna-comment\">\n");
        sb.append("                  <div class=\"qna-comment-slipp\">\n");
        sb.append("                      <p class=\"qna-comment-count\"><strong>2</strong>개의 의견</p>\n");
        sb.append("                      <div class=\"qna-comment-slipp-articles\">\n");
        sb.append("\n");
        sb.append("                          <article class=\"article\" id=\"answer-1405\">\n");
        sb.append("                              <div class=\"article-header\">\n");
        sb.append("                                  <div class=\"article-header-thumb\">\n");
        sb.append("                                      <img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">\n");
        sb.append("                                  </div>\n");
        sb.append("                                  <div class=\"article-header-text\">\n");
        sb.append("                                      <a href=\"/users/1/자바지기\" class=\"article-author-name\">자바지기</a>\n");
        sb.append("                                      <a href=\"#answer-1434\" class=\"article-header-time\" title=\"퍼머링크\">\n");
        sb.append("                                          2016-01-12 14:06\n");
        sb.append("                                      </a>\n");
        sb.append("                                  </div>\n");
        sb.append("                              </div>\n");
        sb.append("                              <div class=\"article-doc comment-doc\">\n");
        sb.append("                                  <p>이 글만으로는 원인 파악하기 힘들겠다. 소스 코드와 설정을 단순화해서 공유해 주면 같이 디버깅해줄 수도 있겠다.</p>\n");
        sb.append("                              </div>\n");
        sb.append("                              <div class=\"article-utils\">\n");
        sb.append("                                  <ul class=\"article-utils-list\">\n");
        sb.append("                                      <li>\n");
        sb.append("                                          <a class=\"link-modify-article\" href=\"/questions/413/answers/1405/form\">수정</a>\n");
        sb.append("                                      </li>\n");
        sb.append("                                      <li>\n");
        sb.append("                                          <form class=\"delete-answer-form\" action=\"/questions/413/answers/1405\" method=\"POST\">\n");
        sb.append("                                              <input type=\"hidden\" name=\"_method\" value=\"DELETE\">\n");
        sb.append("                                              <button type=\"submit\" class=\"delete-answer-button\">삭제</button>\n");
        sb.append("                                          </form>\n");
        sb.append("                                      </li>\n");
        sb.append("                                  </ul>\n");
        sb.append("                              </div>\n");
        sb.append("                          </article>\n");
        sb.append("                          <article class=\"article\" id=\"answer-1406\">\n");
        sb.append("                              <div class=\"article-header\">\n");
        sb.append("                                  <div class=\"article-header-thumb\">\n");
        sb.append("                                      <img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">\n");
        sb.append("                                  </div>\n");
        sb.append("                                  <div class=\"article-header-text\">\n");
        sb.append("                                      <a href=\"/users/1/자바지기\" class=\"article-author-name\">자바지기</a>\n");
        sb.append("                                      <a href=\"#answer-1434\" class=\"article-header-time\" title=\"퍼머링크\">\n");
        sb.append("                                          2016-01-12 14:06\n");
        sb.append("                                      </a>\n");
        sb.append("                                  </div>\n");
        sb.append("                              </div>\n");
        sb.append("                              <div class=\"article-doc comment-doc\">\n");
        sb.append("                                  <p>이 글만으로는 원인 파악하기 힘들겠다. 소스 코드와 설정을 단순화해서 공유해 주면 같이 디버깅해줄 수도 있겠다.</p>\n");
        sb.append("                              </div>\n");
        sb.append("                              <div class=\"article-utils\">\n");
        sb.append("                                  <ul class=\"article-utils-list\">\n");
        sb.append("                                      <li>\n");
        sb.append("                                          <a class=\"link-modify-article\" href=\"/questions/413/answers/1405/form\">수정</a>\n");
        sb.append("                                      </li>\n");
        sb.append("                                      <li>\n");
        sb.append("                                          <form class=\"delete-answer-form\" action=\"/questions/413/answers/1405\" method=\"POST\">\n");
        sb.append("                                              <input type=\"hidden\" name=\"_method\" value=\"DELETE\">\n");
        sb.append("                                              <button type=\"submit\" class=\"delete-answer-button\">삭제</button>\n");
        sb.append("                                          </form>\n");
        sb.append("                                      </li>\n");
        sb.append("                                  </ul>\n");
        sb.append("                              </div>\n");
        sb.append("                          </article>\n");
        sb.append("                          <form class=\"answer-form\">\n");
        sb.append("                              <div class=\"form-group\" style=\"padding:14px;\">\n");
        sb.append("                                  <textarea class=\"form-control\" placeholder=\"Update your status\"></textarea>\n");
        sb.append("                              </div>\n");
        sb.append("                              <button class=\"btn btn-success pull-right\" type=\"button\">답변하기</button>\n");
        sb.append("                              <div class=\"clearfix\" />\n");
        sb.append("                          </form>\n");
        sb.append("                      </div>\n");
        sb.append("                  </div>\n");
        sb.append("              </div>\n");
        sb.append("          </div>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("</div>\n");
        sb.append("\n");
        sb.append("<script type=\"text/template\" id=\"answerTemplate\">\n");
        sb.append("\t<article class=\"article\">\n");
        sb.append("\t\t<div class=\"article-header\">\n");
        sb.append("\t\t\t<div class=\"article-header-thumb\">\n");
        sb.append("\t\t\t\t<img src=\"https://graph.facebook.com/v2.3/1324855987/picture\" class=\"article-author-thumb\" alt=\"\">\n");
        sb.append("\t\t\t</div>\n");
        sb.append("\t\t\t<div class=\"article-header-text\">\n");
        sb.append("\t\t\t\t<a href=\"#\" class=\"article-author-name\">{0}</a>\n");
        sb.append("\t\t\t\t<div class=\"article-header-time\">{1}</div>\n");
        sb.append("\t\t\t</div>\n");
        sb.append("\t\t</div>\n");
        sb.append("\t\t<div class=\"article-doc comment-doc\">\n");
        sb.append("\t\t\t{2}\n");
        sb.append("\t\t</div>\n");
        sb.append("\t\t<div class=\"article-utils\">\n");
        sb.append("\t\t<ul class=\"article-utils-list\">\n");
        sb.append("\t\t\t<li>\n");
        sb.append("\t\t\t\t<a class=\"link-modify-article\" href=\"/api/questions/{3}/answers/{4}/form\">수정</a>\t\t\t\t\n");
        sb.append("\t\t\t</li>\n");
        sb.append("\t\t\t<li>\n");
        sb.append("\t\t\t\t<form class=\"delete-answer-form\" action=\"/api/questions/{3}/answers/{4}\" method=\"POST\">\n");
        sb.append("\t\t\t\t\t<input type=\"hidden\" name=\"_method\" value=\"DELETE\">\n");
        sb.append("                     <button type=\"submit\" class=\"delete-answer-button\">삭제</button>\n");
        sb.append("\t\t\t\t</form>\n");
        sb.append("\t\t\t</li>\n");
        sb.append("\t\t</ul>\n");
        sb.append("\t\t</div>\n");
        sb.append("\t</article>\n");
        sb.append("</script>\n");
        sb.append("\n");
        sb.append("<!-- script references -->\n");
        sb.append("<script src=\"../js/jquery-2.2.0.min.js\"></script>\n");
        sb.append("<script src=\"../js/bootstrap.min.js\"></script>\n");
        sb.append("<script src=\"../js/scripts.js\"></script>\n");
        sb.append("\t</body>\n");
        sb.append("</html>");

        return sb.toString();
    }
}
